### ISSUE TITLE
Can't recruit in First Dungeon (Crowded rest) despite UI saying otherwise

### ISSUE THREAD

**Issue by Morbidtax0175** [Voros-Roka/EoS-Patches#1]
I'll say first I'm running a randomized Rom with this patch which might have some effect on this, but for whatever reason the starting dungeon claims i'm able to recruit but I haven't been able to despite a recruitment item on and 7ish runs. I checked the dungeon on skytemple and it says I can't recruit so i'm not sure why it's saying otherwise.
Not really sure how to show the file but if you need it let me know how.

**Comment by Voros-Roka** [comment]
Looked at the code and it seems there are two flags that tell the game if recruitment is allowed in a dungeon. One is for static dungeon restrictions (I guess this is what you see in skytemple) and the other flag is extra during a run through the dungeon.
I only checked the runtime flag assuming the static one is included ...

Thx for pointing that out, will be fixed in the next version! (properly next weekend)

**Comment by Morbidtax0175** [comment]
Found another interesting thing related to this it seems multi layer dungeons count each layer separate for recruiting while the counter doesn't though that may be related to what you said earlier

**Comment by Voros-Roka** [comment]
At the moment only the individial dungeons count and not the dungeon groups. I added dungeon groups as option to my todo list.

**Comment by Voros-Roka** [comment]
Fixed in 0.0.2
